Rails:
  Enabled: true

AllCops:
  TargetRailsVersion: 5.1
  TargetRubyVersion: 2.5
  Exclude:
    - 'spec/dummy/**/*'
    - 'vendor/bundle/**/*'
    - 'bin/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'db/**/*'

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Naming/FileName:
  Exclude:
  - 'Gemfile'

Style/FrozenStringLiteralComment:
  Enabled: false

